- hosts: all
  tasks:
    - name: Docker repository
      copy:
        src: "/etc/yum.repos.d/docker.repo"
        dest: "/etc/yum.repos.d/docker.repo"

    - name: Install docker
      package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

    - name: Docker SDK for Python
      pip:
        name: "docker"

    - name: Docker service start
      service:
        name: "docker"
        state: started
        enabled: yes

    - name: Pull httpd server image
      docker_image:
        name: "httpd"
        source: pull

    - copy:
        dest: "/var/www/html/index.html"
        content: "It works!"

    - name: launch docker container
      docker_container:
        name: "web_server"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "5678:80"
        interactive: true
        detach: true

